### PR TITLE
Add the GTK frontend

### PR DESCRIPTION
**Pull request by madx**
This PR adds a working Linux frontend to MDR, using WebKit2 + GTK.

### CODE REVIEW

**Comment by halffullheart** [comment]
I was not able to get this to compile on ubuntu (no webkit2 package I could find). Let’s pull it in for now and try to get that working.

**Comment by madx** [comment]
There are many WebKit packages for this on Ubuntu, I'll try to setup a virtualbox to test it. Maybe I'm too much bleeding edge here and should revert to WebKit 1

**Comment by madx** [comment]
Have you tried installing `libwebkitgtk-dev`?

It seems to contain both WebKit 1 & 2

**Comment by halffullheart** [comment]
After installing libwebkitgtk-dev running `pkg-config --list-all | grep webkit` returns this:

```
webkit-1.0
```

**Pull request merged**
