### PR TITLE
linux: Revert to WebKit1

### PR DESCRIPTION
**Pull request by madx**

### CODE REVIEW

**Comment by madx** [comment]
I still have to test this on Ubuntu

**Comment by halffullheart** [comment]
I was able to build and run on Ubuntu with the following modifications to the Rakefile:

``` ruby
linux_flags = [
  `pkg-config --libs --cflags webkit-1.0`.chomp,
  `pkg-config --libs --cflags gtk+-2.0`.chomp
]
```

**Comment by madx** [comment]
I've updated the README, you have to install the `libwebkitgtk-3.0-dev` package. It compiles against GTK+3 which is the current stable, GTK+2 shouldn't be used anymore.

The branch is ready to be merged (the Rakefile is fine as is)

**Comment by halffullheart** [comment]
As of now, this branch will not build in Ubuntu. I get the following error:

``` sh
vagrant@precise32:/vagrant$ rake
Package webkitgtk-3.0 was not found in the pkg-config search path.
```

If I make changes to the compiler flags as mentioned in my previous comment, I can get the build to succeed. I’m not sure how best to fix this without breaking the build for Arch Linux.

Perhaps switching to an autoconf/Make setup would make this kind of thing easier to deal with.

**Comment by madx** [comment]
Have you tried to install `libwebkitgtk-3.0-dev`?

It should be available and I'm running rake without any errors.

2013-11-12t09 09 12

**Comment by madx** [comment]
Hi Daniel,

Could you please try what I said in my previous comment? It should work and enable you to close #21

**Comment by madx** [comment]
Hi Daniel,

Just an update on this, did you try to build it on Ubuntu? Is there any blocking points and if so how could I help?

**Comment by madx** [comment]
Hurray \o/

**Pull request merged**
