### PR TITLE
Build appIcon.png.h

### LINKED ISSUE #15: Can't compile
```
rake
gcc -Wall -g -arch i386 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk -mmacosx-version-min=10.8 -framework Cocoa -framework WebKit  bstrlib.o Reader.o mac/MakeDiffReadable.m -o mdr
mac/MakeDiffReadable.m:5:9: fatal error: '../appIcon.png.h' file not found
#import "../appIcon.png.h"
        ^
1 error generated.
rake aborted!
Command failed with status (1): [gcc -Wall -g -arch i386 -isysroot /Applica...]
/Users/kud/Projects/_kud/mdr/Rakefile:64:in `block in <top (required)>'
Tasks: TOP => default => build => mdr
(See full trace by running task with --trace)
```

### PR DESCRIPTION
**Pull request by madx**
The `appIcon.png.h` should be built as a dependency of `Reader.o` so it's available to all frontends

Closes #15

### CODE REVIEW

**Comment by halffullheart** [comment]
The icon file, appIcon.png is only used by the Mac port. If it becomes required for the other ports then we can add it as a dependency as you suggest. For now, 5d003472b0308e14c1a7a230a7510945db712362 should fix the compile issue, by only adding it as a dependency of the Mac build.

**Comment by madx** [comment]
I should have added that I was going to use it in the Linux version :-)

**Comment by madx** [comment]
Anyway, let's keep your way as the Windows port doesn't need it

**Comment by halffullheart** [comment]
Do you think a different size or style would be better for Linux? I could design a slightly different one for Linux if it would be a better fit.

**Comment by madx** [comment]
I think we should keep the same icon for consistency

Regarding the size, I don't really know yet, I've never done this in GTK, I'll take a look but 96×96 seems sufficient.

**Pull request closed without merging**
